name: CI

on:
  - pull_request

permissions:
  contents: read

jobs:
  test:
    name: "Ruby ${{ matrix.ruby }}, Rails ${{ matrix.gemfile }}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3", "jruby-head"]
        gemfile: ["6.0", "6.1", "7.0", "7.1"]

        exclude:
          - gemfile: "6.0"
            ruby: "3.2"
          - gemfile: "6.0"
            ruby: "3.3"
          - gemfile: "6.1"
            ruby: "3.2"
          - gemfile: "6.1"
            ruby: "3.3"

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.gemfile }}.gemfile
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: "Install Ruby ${{ matrix.ruby }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run specs
        run: bundle exec rspec

      - name: Run standard.rb
        run: bundle exec rake standard
        if: ${{ ! startsWith(matrix.ruby, '2.') }}
